export default {
  page: { minHeight: "100vh", backgroundColor: "#f7fafc", padding: "40px 20px" },
  container: { maxWidth: "800px", margin: "0 auto" },
  header: { display: "flex", justifyContent: "space-between", alignItems: "center", marginBottom: "24px" },
  backButton: { backgroundColor: "#edf2f7", border: "none", padding: "8px 16px", borderRadius: "6px", cursor: "pointer" },
  timer: { backgroundColor: "#fff", padding: "8px 16px", borderRadius: "20px", boxShadow: "0 1px 2px rgba(0,0,0,0.05)" },
  timerText: { fontWeight: "500", color: "#2d3748" },
  className: { fontSize: "28px", fontWeight: "600", marginBottom: "8px" },
  classDesc: { color: "#4a5568", marginBottom: "24px" },
  successMsg: { backgroundColor: "#c6f6d5", color: "#22543d", padding: "12px", borderRadius: "8px", marginBottom: "20px" },
  errorMsg: { backgroundColor: "#fed7d7", color: "#742a2a", padding: "12px", borderRadius: "8px", marginBottom: "20px" },
  questionsList: { display: "flex", flexDirection: "column", gap: "24px" },
  questionCard: { backgroundColor: "#fff", borderRadius: "10px", padding: "20px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" },
  questionTitle: { fontSize: "18px", fontWeight: "500", marginBottom: "12px" },
  textarea: { width: "100%", padding: "10px", border: "1px solid #cbd5e0", borderRadius: "6px", fontSize: "14px", fontFamily: "inherit" },
  buttonRow: { display: "flex", justifyContent: "space-between", alignItems: "center", marginTop: "12px" },
  submitButton: { backgroundColor: "#3182ce", color: "#fff", border: "none", padding: "8px 16px", borderRadius: "6px", cursor: "pointer" },
  savedBadge: { color: "#38a169", fontSize: "14px", fontWeight: "500" },
  loading: { textAlign: "center", padding: "50px", fontSize: "18px" },
  error: { textAlign: "center", padding: "50px", color: "red" },
};