// src/styles/examTimerStyles.js

const examTimerStyles = {
  // ── Student banners ─────────────────────────────────────────
  upcomingBanner: {
    backgroundColor: "#fffbeb",
    border: "1px solid #f59e0b",
    borderRadius: "10px",
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
    gap: "12px",
  },
  activeBanner: {
    backgroundColor: "#f0fdf4",
    border: "1px solid #22c55e",
    borderRadius: "10px",
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
    gap: "12px",
  },
  endedBanner: {
    backgroundColor: "#fef2f2",
    border: "1px solid #ef4444",
    borderRadius: "10px",
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
    gap: "12px",
  },
  // ── Admin schedule banner ───────────────────────────────────
  adminBanner: {
    backgroundColor: "#eff6ff",
    border: "1px solid #3b82f6",
    borderRadius: "10px",
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
    gap: "12px",
  },
  adminNoBanner: {
    backgroundColor: "#f8fafc",
    border: "1px dashed #cbd5e0",
    borderRadius: "10px",
    padding: "14px 20px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: "20px",
    gap: "12px",
  },
  // ── Banner internals ────────────────────────────────────────
  bannerLeft: {
    display: "flex",
    alignItems: "center",
    gap: "12px",
    flex: 1,
  },
  bannerIcon: {
    fontSize: "22px",
    flexShrink: 0,
  },
  bannerTextBlock: {
    display: "flex",
    flexDirection: "column",
    gap: "2px",
  },
  bannerTitle: {
    fontWeight: "600",
    fontSize: "14px",
    color: "#1a202c",
  },
  bannerSubtitle: {
    fontSize: "12px",
    color: "#718096",
  },
  // ── Countdown display ───────────────────────────────────────
  countdown: {
    fontFamily: "'Courier New', Courier, monospace",
    fontSize: "26px",
    fontWeight: "700",
    letterSpacing: "3px",
    flexShrink: 0,
  },
  upcomingCountdown: { color: "#b45309" },
  activeCountdown: { color: "#15803d" },
  endedText: {
    fontSize: "14px",
    fontWeight: "600",
    color: "#dc2626",
  },
  // ── Admin edit button ───────────────────────────────────────
  editScheduleButton: {
    backgroundColor: "transparent",
    border: "1px solid #3b82f6",
    borderRadius: "6px",
    color: "#3b82f6",
    padding: "6px 14px",
    fontSize: "13px",
    cursor: "pointer",
    fontWeight: "500",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  setScheduleButton: {
    backgroundColor: "transparent",
    border: "1px solid #94a3b8",
    borderRadius: "6px",
    color: "#64748b",
    padding: "6px 14px",
    fontSize: "13px",
    cursor: "pointer",
    fontWeight: "500",
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  // ── Locked card (student, exam not active) ──────────────────
  lockedCard: {
    backgroundColor: "#f8fafc",
    border: "1px dashed #cbd5e0",
    borderRadius: "10px",
    padding: "50px 20px",
    textAlign: "center",
  },
  lockedIcon: {
    fontSize: "44px",
    marginBottom: "12px",
  },
  lockedTitle: {
    fontSize: "17px",
    fontWeight: "600",
    color: "#4a5568",
    marginBottom: "8px",
  },
  lockedSubtitle: {
    fontSize: "14px",
    color: "#718096",
  },
  // ── Modal overlay ───────────────────────────────────────────
  modalOverlay: {
    position: "fixed",
    inset: 0,
    backgroundColor: "rgba(0,0,0,0.45)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    zIndex: 1000,
  },
  modal: {
    backgroundColor: "#fff",
    borderRadius: "14px",
    padding: "28px",
    width: "440px",
    maxWidth: "92vw",
    boxShadow: "0 24px 60px rgba(0,0,0,0.18)",
  },
  modalTitle: {
    fontSize: "18px",
    fontWeight: "700",
    color: "#1a202c",
    marginBottom: "4px",
  },
  modalSubtitle: {
    fontSize: "13px",
    color: "#718096",
    marginBottom: "22px",
  },
  fieldGroup: {
    marginBottom: "16px",
  },
  label: {
    display: "block",
    fontSize: "13px",
    fontWeight: "600",
    color: "#4a5568",
    marginBottom: "6px",
  },
  input: {
    width: "100%",
    padding: "9px 12px",
    border: "1px solid #e2e8f0",
    borderRadius: "7px",
    fontSize: "14px",
    color: "#1a202c",
    boxSizing: "border-box",
    outline: "none",
    backgroundColor: "#fff",
  },
  inputHint: {
    fontSize: "11px",
    color: "#a0aec0",
    marginTop: "4px",
  },
  divider: {
    borderTop: "1px solid #e2e8f0",
    margin: "20px 0",
  },
  modalFooter: {
    display: "flex",
    justifyContent: "flex-end",
    gap: "10px",
    marginTop: "24px",
  },
  cancelButton: {
    padding: "9px 18px",
    border: "1px solid #e2e8f0",
    borderRadius: "7px",
    backgroundColor: "#fff",
    color: "#4a5568",
    fontSize: "14px",
    cursor: "pointer",
    fontWeight: "500",
  },
  clearButton: {
    padding: "9px 18px",
    border: "1px solid #feb2b2",
    borderRadius: "7px",
    backgroundColor: "#fff",
    color: "#e53e3e",
    fontSize: "14px",
    cursor: "pointer",
    fontWeight: "500",
  },
  saveButton: {
    padding: "9px 20px",
    border: "none",
    borderRadius: "7px",
    backgroundColor: "#2563eb",
    color: "#fff",
    fontSize: "14px",
    cursor: "pointer",
    fontWeight: "600",
  },
  saveButtonDisabled: {
    padding: "9px 20px",
    border: "none",
    borderRadius: "7px",
    backgroundColor: "#a0aec0",
    color: "#fff",
    fontSize: "14px",
    cursor: "not-allowed",
    fontWeight: "600",
  },
  successMsg: {
    fontSize: "13px",
    color: "#276749",
    backgroundColor: "#c6f6d5",
    padding: "8px 12px",
    borderRadius: "6px",
    marginBottom: "8px",
  },
  errorMsg: {
    fontSize: "13px",
    color: "#c53030",
    backgroundColor: "#fed7d7",
    padding: "8px 12px",
    borderRadius: "6px",
    marginBottom: "8px",
  },
};

export default examTimerStyles;
