export default {
  page: { minHeight: "100vh", backgroundColor: "#f7fafc", padding: "40px 20px" },
  container: { maxWidth: "800px", margin: "0 auto" },
  backButton: { backgroundColor: "#edf2f7", border: "none", padding: "8px 16px", borderRadius: "6px", cursor: "pointer", marginBottom: "20px" },
  className: { fontSize: "28px", fontWeight: "600", marginBottom: "24px" },
  resultCard: { backgroundColor: "#fff", borderRadius: "10px", padding: "20px", marginBottom: "20px", boxShadow: "0 1px 3px rgba(0,0,0,0.1)" },
  questionHeader: { display: "flex", gap: "12px", marginBottom: "12px", borderBottom: "1px solid #e2e8f0", paddingBottom: "8px" },
  questionNumber: { fontWeight: "bold", color: "#4a5568" },
  questionText: { flex: 1 },
  answerSection: { marginBottom: "12px" },
  answerText: { backgroundColor: "#f1f5f9", padding: "12px", borderRadius: "6px", marginTop: "6px" },
  scoreSection: { marginBottom: "8px", color: "#2d3748" },
  feedbackSection: { marginBottom: "8px", color: "#4a5568", fontStyle: "italic" },
  notReleased: { color: "#e53e3e", fontWeight: "500", marginTop: "8px" },
  empty: { textAlign: "center", color: "#718096", padding: "40px" },
  loading: { textAlign: "center", padding: "50px", fontSize: "18px" },
  error: { textAlign: "center", padding: "50px", color: "red" },
  // Add inside the styles object
  graphCard: {
    backgroundColor: "#fff",
    borderRadius: "12px",
    padding: "24px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    marginBottom: "32px",
  },
  graphTitle: {
    fontSize: "18px",
    fontWeight: "600",
    marginBottom: "8px",
  },
  graphSubtitle: {
    fontSize: "14px",
    color: "#718096",
    marginBottom: "24px",
  },
  noResultsBox: {
    textAlign: "center",
    padding: "60px 20px",
    backgroundColor: "#fff",
    borderRadius: "12px",
  },
  noResultsIcon: {
    fontSize: "48px",
    marginBottom: "16px",
  },
  noResultsTitle: {
    fontSize: "20px",
    fontWeight: "600",
    marginBottom: "8px",
  },
  noResultsText: {
    color: "#718096",
  },
  scoreBadge: (score) => ({
    display: "inline-block",
    padding: "4px 10px",
    borderRadius: "20px",
    fontSize: "14px",
    fontWeight: "600",
    backgroundColor: score >= 70 ? "#c6f6d5" : score >= 40 ? "#fefcbf" : "#fed7d7",
    color: score >= 70 ? "#22543d" : score >= 40 ? "#744210" : "#9b2c2c",
  }),
  notAnswered: {
    color: "#a0aec0",
    fontStyle: "italic",
  },
  tableCard: {
    backgroundColor: "#fff",
    borderRadius: "12px",
    padding: "24px",
    boxShadow: "0 1px 3px rgba(0,0,0,0.1)",
    overflowX: "auto",
  },
  tableTitle: {
    fontSize: "18px",
    fontWeight: "600",
    marginBottom: "16px",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
  th: {
    textAlign: "left",
    padding: "12px 8px",
    borderBottom: "2px solid #e2e8f0",
    fontWeight: "600",
  },
  td: {
    padding: "12px 8px",
    borderBottom: "1px solid #e2e8f0",
    verticalAlign: "top",
  },
  tr: {
    "&:hover": { backgroundColor: "#f7fafc" },
  },
  loadingContainer: {
    display: "flex",
    justifyContent: "center",
    alignItems: "center",
    height: "100vh",
    fontSize: "18px",
  },
  errorBox: {
    backgroundColor: "#fed7d7",
    color: "#c53030",
    padding: "20px",
    borderRadius: "8px",
    margin: "20px",
    textAlign: "center",
  },
};